"""One-line invitation issuance and durable client enrollment."""

from __future__ import annotations

import base64
import json
import secrets
import uuid
from dataclasses import dataclass
from datetime import datetime, timedelta, timezone
from pathlib import Path
from typing import Any, Callable
from urllib.parse import urlsplit, urlunsplit

from .config import CentralConfig, _read_external_config, _read_token, _token_bindings
from .domain import canonical_json, is_utc_timestamp, utc_timestamp
from .operations import _secure_atomic_write_json
from .storage import CentralStore


INVITATION_PREFIX = "LR1."
CLAIM_SCHEMA = "life-radio-enrollment-claim-v1"
PROFILE_SCHEMA = "life-radio-client-profile-v1"
INVITATION_SCOPES = {"upload", "dashboard"}


class EnrollmentConfigurationError(RuntimeError):
    pass


@dataclass(frozen=True)
class CreatedInvitation:
    code: str
    invitation_id: str
    expires_at: str
    scope: str


DEVICE_ID_PREFIXES = {
    "desktop": "desktop-",
    "android": "android-install-",
}


def is_valid_enrollment_device_id(value: Any, platform: Any) -> bool:
    """Accept only the installation IDs generated by supported clients."""
    prefix = DEVICE_ID_PREFIXES.get(platform)
    if not isinstance(value, str) or prefix is None or not value.startswith(prefix):
        return False
    try:
        parsed = uuid.UUID(value.removeprefix(prefix))
    except (ValueError, AttributeError):
        return False
    return value == f"{prefix}{parsed}"


def _encode_invitation(payload: dict[str, Any]) -> str:
    encoded = base64.urlsafe_b64encode(
        canonical_json(payload).encode("utf-8")
    ).decode("ascii").rstrip("=")
    return INVITATION_PREFIX + encoded


def decode_invitation(code: str) -> dict[str, Any]:
    if not isinstance(code, str) or not code.startswith(INVITATION_PREFIX):
        raise ValueError("invitation code must start with LR1.")
    encoded = code.removeprefix(INVITATION_PREFIX)
    if not encoded or any(character.isspace() for character in encoded):
        raise ValueError("invitation code is malformed")
    try:
        padding = "=" * (-len(encoded) % 4)
        payload = json.loads(
            base64.b64decode(
                encoded + padding,
                altchars=b"-_",
                validate=True,
            ).decode("utf-8")
        )
    except (ValueError, UnicodeDecodeError, json.JSONDecodeError) as error:
        raise ValueError("invitation code is malformed") from error
    required = {
        "v",
        "invitation_id",
        "central_base_url",
        "invitation_token",
        "scope",
        "expires_at",
    }
    if not isinstance(payload, dict) or set(payload) != required:
        raise ValueError("invitation code contains unsupported fields")
    if payload.get("v") != 1:
        raise ValueError("invitation code version is unsupported")
    try:
        parsed_id = uuid.UUID(str(payload.get("invitation_id")))
    except (ValueError, AttributeError) as error:
        raise ValueError("invitation_id must be a UUID") from error
    if str(payload.get("invitation_id")) != str(parsed_id):
        raise ValueError("invitation_id must use canonical UUID form")
    if payload.get("scope") not in INVITATION_SCOPES:
        raise ValueError("invitation scope is unsupported")
    if not is_utc_timestamp(payload.get("expires_at")):
        raise ValueError("expires_at must be a UTC timestamp")
    token = payload.get("invitation_token")
    if (
        not isinstance(token, str)
        or len(token) < 32
        or len(set(token)) < 8
        or any(character.isspace() for character in token)
    ):
        raise ValueError("invitation token is invalid")
    base_url = payload.get("central_base_url")
    if not isinstance(base_url, str) or not base_url.startswith("https://"):
        raise ValueError("central_base_url must use HTTPS")
    return payload


def create_invitation(
    store: CentralStore,
    *,
    central_base_url: str,
    scope: str = "dashboard",
    lifetime: timedelta = timedelta(hours=24),
    now: datetime | None = None,
) -> CreatedInvitation:
    if scope not in INVITATION_SCOPES:
        raise ValueError("scope must be upload or dashboard")
    if lifetime.total_seconds() <= 0:
        raise ValueError("invitation lifetime must be positive")
    parsed_url = urlsplit(central_base_url.strip())
    if (
        parsed_url.scheme.lower() != "https"
        or not parsed_url.hostname
        or parsed_url.username
        or parsed_url.password
        or parsed_url.path not in {"", "/"}
        or parsed_url.query
        or parsed_url.fragment
    ):
        raise ValueError("central_base_url must be an HTTPS origin")
    normalized_base_url = urlunsplit(
        ("https", parsed_url.netloc.lower(), "", "", "")
    )
    current = (now or datetime.now(timezone.utc)).astimezone(timezone.utc)
    invitation_id = str(uuid.uuid4())
    invitation_token = secrets.token_urlsafe(32)
    expires_at = utc_timestamp(current + lifetime)
    payload = {
        "v": 1,
        "invitation_id": invitation_id,
        "central_base_url": normalized_base_url,
        "invitation_token": invitation_token,
        "scope": scope,
        "expires_at": expires_at,
    }
    code = _encode_invitation(payload)
    store.create_client_invitation(
        invitation_id=invitation_id,
        invitation_token=invitation_token,
        scope=scope,
        central_base_url=normalized_base_url,
        created_at=utc_timestamp(current),
        expires_at=expires_at,
    )
    return CreatedInvitation(code, invitation_id, expires_at, scope)


def validate_claim_payload(payload: Any) -> dict[str, Any]:
    if not isinstance(payload, dict) or set(payload) != {
        "schema_version",
        "invitation_id",
        "device",
    }:
        raise ValueError(
            "claim must contain only schema_version, invitation_id, and device"
        )
    if payload.get("schema_version") != CLAIM_SCHEMA:
        raise ValueError(f"schema_version must be {CLAIM_SCHEMA}")
    invitation_id = payload.get("invitation_id")
    try:
        parsed_id = uuid.UUID(invitation_id)
    except (ValueError, AttributeError, TypeError) as error:
        raise ValueError("invitation_id must be a UUID") from error
    if invitation_id != str(parsed_id):
        raise ValueError("invitation_id must use canonical UUID form")
    device = payload.get("device")
    if not isinstance(device, dict) or set(device) != {
        "device_id",
        "platform",
        "display_name",
    }:
        raise ValueError(
            "device must contain only device_id, platform, and display_name"
        )
    platform = device.get("platform")
    if platform not in DEVICE_ID_PREFIXES:
        raise ValueError("device.platform must be desktop or android")
    if not is_valid_enrollment_device_id(device.get("device_id"), platform):
        raise ValueError(
            "device_id must match the platform's installation-scoped UUID format"
        )
    display_name = device.get("display_name")
    if (
        not isinstance(display_name, str)
        or not display_name.strip()
        or len(display_name.strip()) > 100
    ):
        raise ValueError("device.display_name must contain 1 to 100 characters")
    return {
        "invitation_id": invitation_id,
        "device": {
            "device_id": device["device_id"],
            "platform": platform,
            "display_name": display_name.strip(),
        },
    }


def persistent_credential_provider(
    config: CentralConfig,
) -> Callable[[str, bool, str], tuple[str, str | None]]:
    config_path = config.config_path
    if config_path is None:
        raise EnrollmentConfigurationError(
            "central enrollment requires an external config file"
        )
    target = Path(config_path).expanduser().resolve()

    def provide(
        device_id: str,
        create_allowed: bool,
        scope: str,
    ) -> tuple[str, str | None]:
        external = _read_external_config(str(target))
        bindings = _token_bindings(
            external.get("token_bindings"), source="external config"
        )
        matching = [
            token for token, bound_id in bindings.items() if bound_id == device_id
        ]
        if len(matching) > 1:
            raise EnrollmentConfigurationError(
                "device has multiple permanent upload credentials"
            )
        read_token = _read_token(
            external.get("read_token"), source="external config"
        )
        persisted = CentralConfig.from_environment(
            {"LIFE_RADIO_CENTRAL_CONFIG": str(target)}
        )
        if persisted.database_path.expanduser().resolve() != (
            config.database_path.expanduser().resolve()
        ):
            raise EnrollmentConfigurationError(
                "central config database does not match the running service"
            )
        if scope == "dashboard" and read_token is None:
            raise EnrollmentConfigurationError(
                "dashboard invitations require a configured read token"
            )
        if matching:
            upload_token = matching[0]
        elif not create_allowed:
            raise EnrollmentConfigurationError(
                "claimed invitation credential is missing from central config"
            )
        else:
            upload_token = secrets.token_urlsafe(32)
            while upload_token in bindings or upload_token == read_token:
                upload_token = secrets.token_urlsafe(32)
            bindings[upload_token] = device_id
            updated = dict(external)
            updated["token_bindings"] = bindings
            _secure_atomic_write_json(target, updated)

        return upload_token, read_token

    return provide


def remove_persistent_device_credentials(config: CentralConfig, device_id: str) -> int:
    """Remove every external-config credential for one retired device.

    Runtime authorization is revoked in SQLite first. This persistent cleanup
    prevents a later service restart from seeing a stale secret binding and
    keeps a future invitation free to issue a new token.
    """
    if config.config_path is None:
        raise EnrollmentConfigurationError(
            "device retirement requires a mutable external config file"
        )
    target = Path(config.config_path).expanduser().resolve()
    external = _read_external_config(str(target))
    bindings = _token_bindings(
        external.get("token_bindings"), source="external config"
    )
    retained = {
        token: bound_id for token, bound_id in bindings.items()
        if bound_id != device_id
    }
    removed = len(bindings) - len(retained)
    if removed:
        updated = dict(external)
        updated["token_bindings"] = retained
        _secure_atomic_write_json(target, updated)
    return removed


def claim_invitation(
    store: CentralStore,
    config: CentralConfig,
    *,
    invitation_token: str,
    claim: dict[str, Any],
    now: datetime | None = None,
) -> dict[str, Any]:
    current = (now or datetime.now(timezone.utc)).astimezone(timezone.utc)
    device = claim["device"]

    # Scope is authoritatively loaded and checked inside the store transaction.
    # The provider may expose the read token; the response includes it only for
    # a dashboard-scoped invitation.
    provider = persistent_credential_provider(config)
    result = store.claim_client_invitation(
        invitation_id=claim["invitation_id"],
        invitation_token=invitation_token,
        device_id=device["device_id"],
        platform=device["platform"],
        display_name=device["display_name"],
        claimed_at=utc_timestamp(current),
        credential_provider=provider,
    )
    profile = {
        "schema_version": PROFILE_SCHEMA,
        "central_base_url": result["central_base_url"],
        "device": {
            "device_id": result["device_id"],
            "platform": result["platform"],
            "display_name": result["display_name"],
        },
        "upload_token": result["upload_token"],
        "issued_at": result["issued_at"],
    }
    if result["scope"] == "dashboard":
        profile["read_token"] = result["read_token"]
    return profile
